const dictionary = {
    title: { en: "Math Solver", bn: "গণিত সমাধান" },
    heroTitle: { en: "Integration & Differentiation & Graph problem Solver", bn: "ইন্টিগ্রেশন ও ডিফারেনশিয়েশন ও গ্রাফ সমস্যা সমাধানকারী" },
    heroSub: { en: "Type any expression — as hard as you like — and get the worked-out answer.", bn: "যত কঠিন অংকই হোক, লিখে দাও — উত্তর বের করে দেবে।" },
    modeDiff: { en: "Differentiate (d/dx)", bn: "ডিফারেনশিয়েট (d/dx)" },
    modeInt: { en: "Integrate (∫)", bn: "ইন্টিগ্রেট (∫)" },
    modeGraph: { en: "Graph", bn: "গ্রাফ" },
    exprLabel: { en: "Write your problem here", bn: "তোমার অংকটা এখানে লেখো" },
    xminLabel: { en: "x min", bn: "x ন্যূনতম" },
    xmaxLabel: { en: "x max", bn: "x সর্বোচ্চ" },
    graphTitle: { en: "Graph of the function", bn: "ফাংশনের গ্রাফ" },
    graphBtn: { en: "Plot Graph", bn: "গ্রাফ আঁকো" },
    graphingBtn: { en: "Plotting...", bn: "গ্রাফ আঁকা হচ্ছে..." },
    noPointsMsg: { en: "No real points could be plotted in this range.", bn: "এই সীমায় কোনো বাস্তব বিন্দু পাওয়া যায়নি।" },
    clearBtn: { en: "Clear", bn: "মুছে ফেলো" },
    tabBasic: { en: "Basic", bn: "সাধারণ" },
    tabTrig: { en: "Trig", bn: "ত্রিকোণমিতি" },
    tabHyper: { en: "Inverse & Hyperbolic", bn: "ইনভার্স ও হাইপারবোলিক" },
    tabOther: { en: "Other", bn: "অন্যান্য" },
    typingHint: {
        en: "Tip: use ^ for power (x^2), * or a space for multiplication (2x or 2*x), sqrt(x) for √x, and ln(x) for natural log.",
        bn: "টিপস: পাওয়ারের জন্য ^ (যেমন x^2), গুণের জন্য * অথবা স্পেস (2x বা 2*x), বর্গমূলের জন্য sqrt(x), আর ln(x) দিয়ে স্বাভাবিক লগ লেখো।"
    },
    wrtLabel: { en: "With respect to", bn: "কোন চলরাশির সাপেক্ষে" },
    wrtHint: { en: 'Use "x,y" for a mixed partial derivative', bn: 'মিশ্র আংশিক অন্তরকের জন্য "x,y" লেখো' },
    orderLabel: { en: "Derivative order", bn: "কততম ডেরিভেটিভ" },
    definiteLabel: { en: "Definite integral (with limits)", bn: "নির্দিষ্ট সীমাযুক্ত ইন্টিগ্রেল (Definite)" },
    lowerLabel: { en: "Lower limit", bn: "নিম্ন সীমা" },
    upperLabel: { en: "Upper limit", bn: "ঊর্ধ্ব সীমা" },
    solveBtn: { en: "Solve", bn: "সমাধান করো" },
    solvingBtn: { en: "Solving...", bn: "সমাধান হচ্ছে..." },
    copyBtn: { en: "Copy result", bn: "উত্তর কপি করো" },
    copiedBtn: { en: "Copied!", bn: "কপি হয়েছে!" },
    emptyExprMsg: { en: "Please write a problem first!", bn: "আগে একটা অংক লেখো!" },
    serverErrMsg: { en: "Server connection failed! Please check your internet and try again.", bn: "সার্ভারের সাথে কানেক্ট করা যাচ্ছে না! ইন্টারনেট চেক করে আবার চেষ্টা করো।" },
    statusOk: { en: "Looks good", bn: "ঠিক আছে" },
    statusUnbalancedOpen: { en: "Missing a closing ')'", bn: "একটা ')' বাকি আছে" },
    statusUnbalancedClose: { en: "Extra ')' with no matching '('", bn: "অতিরিক্ত ')' আছে, মিলছে না" },
    statusBadChar: { en: "Contains a character that isn't allowed", bn: "এমন একটা অক্ষর আছে যেটা চলবে না" },
    statusEmpty: { en: "Start typing your expression above", bn: "উপরে তোমার অংকটা লিখতে শুরু করো" }
};
