const dictionary = {
    title: { en: "3D Geometry Solver", bn: "থ্রিডি জ্যামিতি সমাধান" },
    heroTitle: { en: "Three-Dimensional Geometry Solver", bn: "থ্রি-ডাইমেনশনাল জ্যামিতি সমাধান" },
    heroSub: {
        en: "Points, lines, planes, angles, distances — pick a problem type and plug in your numbers.",
        bn: "বিন্দু, রেখা, তল, কোণ, দূরত্ব — যে ধরনের অংক তোমার, সেটা বেছে নিয়ে সংখ্যাগুলো বসিয়ে দাও।"
    },
    categoryLabel: { en: "Category", bn: "বিভাগ" },
    operationLabel: { en: "Problem type", bn: "কোন ধরনের অংক" },
    fillExample: { en: "Fill example values", bn: "উদাহরণ বসাও" },
    clearFields: { en: "Clear", bn: "মুছে ফেলো" },
    solveBtn: { en: "Solve", bn: "সমাধান করো" },
    solvingBtn: { en: "Solving...", bn: "সমাধান হচ্ছে..." },
    showSteps: { en: "Show working", bn: "ধাপগুলো দেখাও" },
    hideSteps: { en: "Hide working", bn: "ধাপগুলো লুকাও" },
    copyBtn: { en: "Copy result", bn: "উত্তর কপি করো" },
    copiedBtn: { en: "Copied!", bn: "কপি হয়েছে!" },
    resultHead: { en: "Result", bn: "ফলাফল" },
    serverErrMsg: { en: "Server connection failed! Please check your internet and try again.", bn: "সার্ভারের সাথে কানেক্ট করা যাচ্ছে না! ইন্টারনেট চেক করে আবার চেষ্টা করো।" },
    formatTitle: { en: "How to type things", bn: "কীভাবে লিখবে" },
    formatPoint: { en: 'A point: three numbers separated by commas — e.g. "1,2,3" or "-2,0,5"', bn: 'একটা বিন্দু: কমা দিয়ে আলাদা করা তিনটে সংখ্যা — যেমন "1,2,3" বা "-2,0,5"' },
    formatDir: { en: 'Direction ratios / normal vector: same format — e.g. "1,-1,2"', bn: 'ডাইরেকশন রেশিও / নরমাল ভেক্টর: একই ফরম্যাট — যেমন "1,-1,2"' },
    formatAdvanced: { en: 'You can use fractions, √ and π inside a coordinate too — e.g. "sqrt(2),1/2,-pi"', bn: 'কোঅর্ডিনেটের ভেতরে ভগ্নাংশ, √ আর π-ও লেখা যায় — যেমন "sqrt(2),1/2,-pi"' },

    catAll: { en: "All", bn: "সব" },
    catPointsLines: { en: "Points & Lines", bn: "বিন্দু ও রেখা" },
    catPlanes: { en: "Planes", bn: "তল" },
    catAngles: { en: "Angles", bn: "কোণ" },
    catDistances: { en: "Distances & Perpendiculars", bn: "দূরত্ব ও লম্ব" },
    catSpecial: { en: "Special", bn: "বিশেষ" },

    pointDirectionMode: { en: "Point + direction", bn: "বিন্দু + ডাইরেকশন" },
    twoPointsMode: { en: "Two points", bn: "দুটো বিন্দু" },
    pointNormalMode: { en: "Point + normal", bn: "বিন্দু + নরমাল" },
    threePointsMode: { en: "Three points", bn: "তিনটে বিন্দু" },
    internalMode: { en: "Internal", bn: "ইন্টার্নাল" },
    externalMode: { en: "External", bn: "এক্সটার্নাল" },

    fieldPoint1: { en: "Point 1", bn: "বিন্দু ১" },
    fieldPoint2: { en: "Point 2", bn: "বিন্দু ২" },
    fieldPoint3: { en: "Point 3", bn: "বিন্দু ৩" },
    fieldPoint4: { en: "Point 4", bn: "বিন্দু ৪" },
    fieldPoint: { en: "Point", bn: "বিন্দু" },
    fieldM: { en: "m", bn: "m" },
    fieldN: { en: "n", bn: "n" },
    fieldMode: { en: "Division type", bn: "ভাগের ধরন" },
    fieldDirection1: { en: "Direction ratios (line 1)", bn: "ডাইরেকশন রেশিও (রেখা ১)" },
    fieldDirection2: { en: "Direction ratios (line 2)", bn: "ডাইরেকশন রেশিও (রেখা ২)" },
    fieldNormal1: { en: "Normal vector (plane 1)", bn: "নরমাল ভেক্টর (তল ১)" },
    fieldNormal2: { en: "Normal vector (plane 2)", bn: "নরমাল ভেক্টর (তল ২)" },
    fieldDirection: { en: "Direction ratios (of the line)", bn: "ডাইরেকশন রেশিও (রেখার)" },
    fieldNormal: { en: "Normal vector (of the plane)", bn: "নরমাল ভেক্টর (তলের)" },
    fieldPointA: { en: "Point A", bn: "বিন্দু A" },
    fieldPointB: { en: "Point B", bn: "বিন্দু B" },

    groupPlane: { en: "Plane", bn: "তল" },
    groupLine: { en: "Line", bn: "রেখা" },
    groupLine1: { en: "Line 1", bn: "রেখা ১" },
    groupLine2: { en: "Line 2", bn: "রেখা ২" },

    opDistancePoints: { en: "Distance between two points", bn: "দুটো বিন্দুর মধ্যে দূরত্ব" },
    opSectionFormula: { en: "Section formula (divides a segment in a ratio)", bn: "সেকশন ফর্মুলা (নির্দিষ্ট অনুপাতে ভাগ)" },
    opDirectionRatios: { en: "Direction ratios & cosines of a line", bn: "একটা রেখার ডাইরেকশন রেশিও ও কসাইন" },
    opLineTwoPoints: { en: "Equation of a line through two points", bn: "দুটো বিন্দু দিয়ে যাওয়া রেখার সমীকরণ" },
    opPlaneThreePoints: { en: "Equation of a plane through three points", bn: "তিনটে বিন্দু দিয়ে যাওয়া তলের সমীকরণ" },
    opPlanePointNormal: { en: "Equation of a plane (point + normal)", bn: "তলের সমীকরণ (বিন্দু + নরমাল দিয়ে)" },
    opAngleLines: { en: "Angle between two lines", bn: "দুটো রেখার মধ্যে কোণ" },
    opAnglePlanes: { en: "Angle between two planes", bn: "দুটো তলের মধ্যে কোণ" },
    opAngleLinePlane: { en: "Angle between a line and a plane", bn: "একটা রেখা ও তলের মধ্যে কোণ" },
    opDistPointPlane: { en: "Distance of a point from a plane", bn: "একটা বিন্দু থেকে তলের দূরত্ব" },
    opDistPointLine: { en: "Distance of a point from a line", bn: "একটা বিন্দু থেকে রেখার দূরত্ব" },
    opShortestDist: { en: "Shortest distance between two lines", bn: "দুটো রেখার মধ্যে সর্বনিম্ন দূরত্ব" },
    opFootPlane: { en: "Foot of perpendicular — point to a plane", bn: "লম্বের পাদবিন্দু — বিন্দু থেকে তলে" },
    opFootLine: { en: "Foot of perpendicular — point to a line", bn: "লম্বের পাদবিন্দু — বিন্দু থেকে রেখায়" },
    opImagePlane: { en: "Image (reflection) of a point in a plane", bn: "তলে একটা বিন্দুর প্রতিবিম্ব" },
    opCoplanarity: { en: "Check if four points are coplanar", bn: "চারটে বিন্দু একই তলে আছে কিনা" },
    opIntersection: { en: "Intersection of a line and a plane", bn: "একটা রেখা ও তলের ছেদবিন্দু" }
};
