const dictionary = {
    title: { en: "PhysicsLab", bn: "ফিজিক্স ল্যাব" },
    heroTitle: { en: "Explore the Laws of Universe", bn: "মহাবিশ্বের নিয়মগুলো জানুন" },
    heroSub: { en: "Search and calculate complex formulas instantly.", bn: "যেকোনো কঠিন সূত্র খুঁজুন এবং নিমেষে হিসাব করুন।" },
    searchPlaceholder: { en: "Search formulas...", bn: "সূত্র খুঁজুন (যেমন: Force)..." },
    availableFormulas: { en: "Available Formulas", bn: "সকল সূত্র" },
    calcBtn: { en: "Calculate Result", bn: "ফলাফল নির্ণয় করুন" },
    targetLabel: { en: "What do you want to find?", bn: "কী বের করতে চান?" },
    targetDefault: { en: "-- Select Target --", bn: "-- নির্বাচন করুন --" },
    scientistTitle: { en: "Legendary Physicists", bn: "মহান পদার্থবিজ্ঞানীগণ" },


  tabBasic: { en: "Basic Formulas", bn: "সাধারণ সূত্র" },
    tabSmart: { en: "Smart AI Solver", bn: "স্মার্ট এ.আই সলভার" },
    smartTitle: { en: "Smart Physics Solver", bn: "স্মার্ট ফিজিক্স সলভার" },
    smartTargetLabel: { en: "What do you want to find?", bn: "আপনি কী বের করতে চান?" },
    smartKnownLabel: { en: "Add known values:", bn: "জানা মানগুলো যোগ করুন:" },
    addVarBtn: { en: "+ Add Value", bn: "+ নতুন মান যোগ করুন" },
    solveBtn: { en: "Calculate Result", bn: "ফলাফল নির্ণয় করুন" }
};


const physicsFormulas = {
    "newtons_second_law": {
        id: "newtons_second_law", 
        all_variables: ["F", "m", "a"],
        name: { en: "Newton's Second Law", bn: "নিউটনের দ্বিতীয় সূত্র" },
        formula: "F = ma",
        tags: ["newton", "force", "mass", "acceleration", "বল", "ভর", "ত্বরণ"]
    },
    "kinetic_energy": {
        id: "kinetic_energy", 
        all_variables: ["KE", "m", "v"],
        name: { en: "Kinetic Energy", bn: "গতিশক্তি" },
        formula: "KE = ½mv²",
        tags: ["energy", "kinetic", "velocity", "শক্তি", "গতি", "বেগ"]
    },
    "ohms_law": {
        id: "ohms_law", 
        all_variables: ["V", "I", "R"],
        name: { en: "Ohm's Law", bn: "ওমের সূত্র" },
        formula: "V = IR",
        tags: ["ohm", "voltage", "current", "resistance", "ভোল্টেজ", "বিদ্যুৎ", "রোধ"]
    }
};
const variableGlossary = {
    v: { en: "Final velocity", bn: "অন্তিম বেগ" },
    u: { en: "Initial velocity", bn: "প্রাথমিক বেগ" },
    a: { en: "Acceleration", bn: "ত্বরণ" },
    t: { en: "Time", bn: "সময়" },
    s: { en: "Displacement", bn: "সরণ" },
    F: { en: "Force", bn: "বল" },
    m: { en: "Mass", bn: "ভর" },
    g: { en: "Acceleration due to gravity", bn: "মহাকর্ষীয় ত্বরণ" },
    p: { en: "Momentum", bn: "ভরবেগ" },
    W: { en: "Work", bn: "কাজ" },
    KE: { en: "Kinetic energy", bn: "গতিশক্তি" },
    PE: { en: "Potential energy", bn: "স্থিতিশক্তি" },
    P_power: { en: "Power", bn: "ক্ষমতা" },
    r: { en: "Radius / distance", bn: "ব্যাসার্ধ / দূরত্ব" },
    omega: { en: "Angular velocity", bn: "কৌণিক বেগ" },
    T: { en: "Time period", bn: "পর্যায়কাল" },
    G: { en: "Gravitational constant", bn: "মহাকর্ষীয় ধ্রুবক" },
    M: { en: "Mass of large body (planet/star)", bn: "বৃহৎ বস্তুর (গ্রহ/তারা) ভর" },
    R: { en: "Radius of large body / gas constant", bn: "বৃহৎ বস্তুর ব্যাসার্ধ / গ্যাস ধ্রুবক" },
    tau: { en: "Torque", bn: "টর্ক" },
    
    L: { en: "Angular momentum / length", bn: "কৌণিক ভরবেগ / দৈর্ঘ্য" },
    
    x: { en: "Displacement from equilibrium", bn: "সাম্যাবস্থা থেকে সরণ" },
    A: { en: "Amplitude / area", bn: "বিস্তার / ক্ষেত্রফল" },
    f: { en: "Frequency", bn: "কম্পাঙ্ক" },
    lambda_w: { en: "Wavelength", bn: "তরঙ্গদৈর্ঘ্য" },
    Y: { en: "Young's modulus", bn: "ইয়ং-এর গুণাঙ্ক" },
    P: { en: "Pressure", bn: "চাপ" },
    rho: { en: "Density", bn: "ঘনত্ব" },
    Q: { en: "Heat", bn: "তাপ" },
    c: { en: "Specific heat / speed of light", bn: "আপেক্ষিক তাপ / আলোর বেগ" },
    dT: { en: "Change in temperature", bn: "তাপমাত্রার পরিবর্তন" },
    n: { en: "Number of moles / refractive index", bn: "মোল সংখ্যা / প্রতিসরাঙ্ক" },
    q: { en: "Charge", bn: "চার্জ" },
    V: { en: "Voltage / Volume", bn: "ভোল্টেজ / আয়তন" },
    C: { en: "Capacitance", bn: "ধারকত্ব" },
    I: { en: "Current / Moment of inertia", bn: "প্রবাহমাত্রা / জড়তার ভ্রামক" },
    Z: { en: "Atomic number / Impedance", bn: "পারমাণবিক সংখ্যা / প্রতিবন্ধকতা" },
    k: { en: "Spring constant / Coulomb's constant", bn: "স্প্রিং ধ্রুবক / কুলম্বের ধ্রুবক" },
    B: { en: "Magnetic field", bn: "চৌম্বক ক্ষেত্র" },
    h: { en: "Height / Planck's constant", bn: "উচ্চতা / প্লাঙ্ক ধ্রুবক" },
    // --- বাকি সব ভ্যারিয়েবল ---
    W_weight: { en: "Weight", bn: "ওজন" },
    impulse: { en: "Impulse", bn: "আবেগ" },
    F_friction: { en: "Friction force", bn: "ঘর্ষণ বল" },
    mu: { en: "Coefficient of friction", bn: "ঘর্ষণ গুণাঙ্ক" },
    N: { en: "Normal force", bn: "লম্ব প্রতিক্রিয়া বল" },
    cos_theta: { en: "Cosine of angle θ", bn: "θ কোণের কোসাইন" },
    sin_theta: { en: "Sine of angle θ", bn: "θ কোণের সাইন" },
    PE_spring: { en: "Spring potential energy", bn: "স্প্রিং স্থিতিশক্তি" },
    a_c: { en: "Centripetal acceleration", bn: "কেন্দ্রমুখী ত্বরণ" },
    F_c: { en: "Centripetal force", bn: "কেন্দ্রমুখী বল" },
    m1: { en: "Mass of object 1", bn: "১ম বস্তুর ভর" },
    m2: { en: "Mass of object 2", bn: "২য় বস্তুর ভর" },
    alpha: { en: "Angular acceleration / expansion coefficient", bn: "কৌণিক ত্বরণ / প্রসারণ গুণাঙ্ক" },
    v_max: { en: "Maximum velocity", bn: "সর্বোচ্চ বেগ" },
    a_max: { en: "Maximum acceleration", bn: "সর্বোচ্চ ত্বরণ" },
    T_tension: { en: "Tension in string", bn: "তারের টান" },
    mu_linear: { en: "Linear mass density", bn: "রৈখিক ভর ঘনত্ব" },
    beat_f: { en: "Beat frequency", bn: "বিট কম্পাঙ্ক" },
    f1: { en: "Frequency 1", bn: "১ম কম্পাঙ্ক" },
    f2: { en: "Frequency 2", bn: "২য় কম্পাঙ্ক" },
    delta_L: { en: "Change in length", bn: "দৈর্ঘ্যের পরিবর্তন" },
    F_b: { en: "Buoyant force", bn: "উর্ধ্বমুখী বল" },
    A1: { en: "Area 1", bn: "১ম ক্ষেত্রফল" },
    v1: { en: "Velocity 1", bn: "১ম বেগ" },
    A2: { en: "Area 2", bn: "২য় ক্ষেত্রফল" },
    v2: { en: "Velocity 2", bn: "২য় বেগ" },
    L_latent: { en: "Specific latent heat", bn: "আপেক্ষিক সুপ্ত তাপ" },
    dL: { en: "Change in length", bn: "দৈর্ঘ্যের পরিবর্তন" },
    efficiency_carnot: { en: "Carnot efficiency", bn: "কার্নো দক্ষতা" },
    T1: { en: "Temperature of hot reservoir", bn: "উষ্ণ আধারের তাপমাত্রা" },
    T2: { en: "Temperature of cold reservoir", bn: "শীতল আধারের তাপমাত্রা" },
    v_img: { en: "Image distance", bn: "প্রতিবিম্বের দূরত্ব" },
    u_obj: { en: "Object distance", bn: "বস্তুর দূরত্ব" },
    m_mag: { en: "Magnification", bn: "বিবর্ধন" },
    h_i: { en: "Image height", bn: "প্রতিবিম্বের উচ্চতা" },
    h_o: { en: "Object height", bn: "বস্তুর উচ্চতা" },
    P_lens: { en: "Power of lens", bn: "লেন্সের ক্ষমতা" },
    n1: { en: "Refractive index of medium 1", bn: "১ম মাধ্যমের প্রতিসরাঙ্ক" },
    n2: { en: "Refractive index of medium 2", bn: "২য় মাধ্যমের প্রতিসরাঙ্ক" },
    sin_i: { en: "Sine of angle of incidence", bn: "আপতন কোণের সাইন" },
    sin_r: { en: "Sine of angle of refraction", bn: "প্রতিসরণ কোণের সাইন" },
    sin_c: { en: "Sine of critical angle", bn: "সংকট কোণের সাইন" },
    beta: { en: "Fringe width", bn: "পটি প্রস্থ" },
    D_screen: { en: "Slit-to-screen distance", bn: "চির থেকে পর্দার দূরত্ব" },
    d_slit: { en: "Slit separation", bn: "চিরের ব্যবধান" },
    q1: { en: "Charge 1", bn: "১ম চার্জ" },
    q2: { en: "Charge 2", bn: "২য় চার্জ" },
    E_field: { en: "Electric field", bn: "তড়িৎ ক্ষেত্র" },
    epsilon0: { en: "Permittivity of free space", bn: "শূন্যস্থানের ভেদনযোগ্যতা" },
    d: { en: "Separation / thickness", bn: "ব্যবধান / পুরুত্ব" },
    U_cap: { en: "Energy stored in capacitor", bn: "ধারকে সঞ্চিত শক্তি" },
    r_int: { en: "Internal resistance", bn: "আভ্যন্তরীণ রোধ" },
    E_emf: { en: "EMF", bn: "তড়িৎচালক বল" },
    mu0: { en: "Permeability of free space", bn: "শূন্যস্থানের ভেদ্যতা" },
    n_turns: { en: "Number of turns", bn: "প্যাঁচের সংখ্যা" },
    emf: { en: "Electromotive force", bn: "তড়িৎচালক বল" },
    d_phi: { en: "Change in magnetic flux", bn: "চৌম্বক ফ্লাক্সের পরিবর্তন" },
    dt: { en: "Change in time", bn: "সময়ের পরিবর্তন" },
    I_rms: { en: "RMS current", bn: "RMS প্রবাহ" },
    I0: { en: "Peak current", bn: "সর্বোচ্চ প্রবাহ" },
    X_L: { en: "Inductive reactance", bn: "আবেশীয় প্রতিবন্ধকতা" },
    X_C: { en: "Capacitive reactance", bn: "ধারকীয় প্রতিবন্ধকতা" },
    L_ind: { en: "Inductance", bn: "আবেশাঙ্ক" },
    f0: { en: "Resonant frequency", bn: "অনুরণন কম্পাঙ্ক" },
    E_photon: { en: "Photon energy", bn: "ফোটন শক্তি" },
    KE_max: { en: "Max kinetic energy (photoelectrons)", bn: "সর্বোচ্চ গতিশক্তি (আলোক-ইলেকট্রন)" },
    phi_work: { en: "Work function", bn: "কার্যাপেক্ষক" },
    lambda_debroglie: { en: "de Broglie wavelength", bn: "দ্রব্রগলি তরঙ্গদৈর্ঘ্য" },
    E_n: { en: "Energy of nth orbit", bn: "n-তম কক্ষপথের শক্তি" },
    T_half: { en: "Half-life", bn: "অর্ধায়ু" },
    lambda_decay: { en: "Decay constant", bn: "ক্ষয় ধ্রুবক" },
    E_rest: { en: "Rest mass energy", bn: "স্থিতি ভর-শক্তি" },
};